### ISSUE TITLE
Please read this before you create the issue 😊

### ISSUE THREAD

**Issue by Kuuuuuuuu** [unknownsrc/tokens#10]
Please read FAQ first before you create issue. 

This repo actually help you before your servers got nuke!

**Comment by CreatorvsIShere** [comment]
yeah and idc bc i deleted my server before they found the token slay bitch

**Comment by skidmaster69420** [comment]
> yeah and idc bc i deleted my server before they found the token slay bitch

Dude... what a cheap excuse to get rid of your furry roleplay server. At least come up with something original.
