### ISSUE TITLE
Read Me

### ISSUE THREAD

**Issue by huhvzi** [unknownsrc/tokens#12]
They didn't hack you, they found these tokens on a website online. Please do not send them hate, I did find the token somewhere, They put it here so that discord detects it and resets the token. Thanks!

**Comment by CreatorvsIShere** [comment]
hell nah roblox bedwars player that hes teaming with some kids and idc abt them go nuke my server find more tokens and try finding my and good luck nuking my  server

**Comment by unknownsrc** [comment]
> hell nah roblox bedwars player that hes teaming with some kids and idc abt them go nuke my server find more tokens and try finding my and good luck nuking my server

sssshhhh baby ssshhhhh

**Comment by skidmaster69420** [comment]
> hell nah roblox bedwars player that hes teaming with some kids and idc abt them go nuke my server find more tokens and try finding my and good luck nuking my server

HOW DARE YOU? You are disrespecting the true legacy of hypixel by playing a cheap knockoff bedwars on roblox. You are infringing on the hypixel gods, so I dare you... I DARE YOU to go play on hypixel and buy all of their sub options, or else... 

I'll destroy your bed, IRL.

sent from MyMinecraft client sponsored by Hypixel.
