### ISSUE TITLE
Thanks for the notifaction 

### ISSUE THREAD

**Issue by YousefM0** [unknownsrc/tokens#14]
is there a way to gain more information where you got a token form ?

**Comment by unknownsrc** [comment]
https://github.com/unknownsrc/tokens/blob/main/FAQ.md

**Comment by skidmaster69420** [comment]
We find tokens on AOL instant messenger, local facebook groups and walmart bathrooms. Don't ask for "Steve" in a walmart bathroom. Just. Don't.

- Steve.
