### ISSUE TITLE
Lmao

### ISSUE THREAD

**Issue by skiddiegit** [unknownsrc/tokens#17]
You guys are kids u could sell that tool for hundred of money but then u did this shit gaining 0$ get a brain and sell me the tool

**Comment by User9684** [comment]
You aren't getting the tool skiddie

**Comment by IMarkoMC** [comment]
Say you're a skid without saying you're a skid

**Comment by ghost** [comment]
username checks out :tada:

**Comment by unknownsrc** [comment]
> You guys are kids u could sell that tool for hundred of money but then u did this shit gaining 0$ get a brain and sell me the tool

lmfao

**Comment by unknownsrc** [comment]
ill actually pin this because i love this kid too much

**Comment by unknownsrc** [comment]
https://web.archive.org/web/20220819152132/https://github.com/unknownsrc/tokens/issues/17

**Comment by skidmaster69420** [comment]
Hi there.

Thank you for the suggestion that we could sell this tool and make a lot of money with it. However what you don't know, is that this tool is funded with your college fund from your parents. They have already seen how much of a failure you are, hence they have graciously donated it towards this project. Seeing your comment, they have been re-affirmed in their commitment. Which made them donate once more.

We wish to thank you from the bottom of our heart for being that stupid, you have funded the entire project with it.
