### ISSUE TITLE
Yeah, I reset my shit

### ISSUE THREAD

**Issue by RTgamerr** [unknownsrc/tokens#2]
Yeah, I will just reset my token for the bot because it's only for private use and if anyone maliciously keeps using it over and over that might get the people who are hosting nuke bots banned

**Comment by RealmKebab** [comment]
shut the fuck up
shes invalidating it so discord atuomatically resets it

**Comment by unknownsrc** [comment]
Smart person above me

**Comment by skidmaster69420** [comment]
Nuked?
That reminds me of Japan. Let me tell you about my favorite Hentai. So basically the plot goes as following, America-senpai developed a crush upon Japan-san. But America-senpai was a yandere, so she decided to playfully kill her crush Japan-san. Japan-san was just living a normal student life but then got absolutely fucked by America-senpai's huge nuke.
