### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by phishontop** [unknownsrc/tokens#20]
the world needs more people like you. I use to find peoples webhooks, discord tokens and even password and database keys on repl.it
left in plain text, you just helped educate thousands of people.

**Comment by User9684** [comment]
yessir

**Comment by unknownsrc** [comment]
#queen

**Comment by skidmaster69420** [comment]
Hello there,

we at Skidmaster69420 LLC wish to reward you with a military star of honor, however our boss is too much of a cheapskate to grant you that. So please just take our compliments instead.

Yours,
Unpaid Intern
Skidmaster69420 LLC

Edit: Boss slapped me.
