### ISSUE TITLE
can u not fking post my discord bot token u retard

### ISSUE THREAD

**Issue by DadLeftMeLOL** [unknownsrc/tokens#5]
dumbass

**Comment by dystoqia** [comment]
ur the one who used a bot template from the internet

**Comment by Kellerrocks** [comment]
shes helping u

**Comment by ghost** [comment]
> dumbass

Just use a .env file - it's not even that hard. Check out [dotenv](https://www.npmjs.com/package/dotenv) on npm.

**Comment by unknownsrc** [comment]
smart person above me

**Comment by skidmaster69420** [comment]
I felt so insulted by this issue, that I had to sign a police restraining order. However, that restraint order was not towards you. IT WAS TOWARDS MYSELF FROM THE POLICE. They told me, and I quote "Never, EVER approach us ever again, contact the other police stations in different cities to get help with your concerns. So. Basically. YOU GOT ME BANNED FROM THE POLICE. I didn't even know such a thing was possible, but you made it possible. They told me how they suffered reading your issue badly, so badly... they had to check in to the hospital for check ups.
