### ISSUE TITLE
can u add me back on discord thanks for ur help

### ISSUE THREAD

**Issue by Kellerrocks** [unknownsrc/tokens#6]

**Comment by unknownsrc** [comment]
Accepted all friend requests I had

**Comment by D3MOX** [comment]
> Accepted all friend requests I had

yo how tf u be pinging bare ppls tokens lol u could use this as an advertisement of your server add me Demox#2422

**Comment by unknownsrc** [comment]
> > Accepted all friend requests I had
> 
> yo how tf u be pinging bare ppls tokens lol u could use this as an advertisement of your server add me Demox#2422

Thats clown behaviour...

**Comment by D3MOX** [comment]
i thought u were pinging ppls tokens for no reason mb

**Comment by unknownsrc** [comment]
clownery

**Comment by skidmaster69420** [comment]
> yo how tf u be pinging bare ppls tokens lol u could use this as an advertisement of your server add me Demox#2422

The only thing we condone as advertisement is Raid Shadow: Legends, the free mobile game available on every mobile device on this planet, use this link for extra points.

http://internetpolice.us/#if_you_report_yourself+you+will+earn+extra+points+thank+you_in_advance
