### ISSUE TITLE
stop

### ISSUE THREAD

**Issue by phoonk** [unknownsrc/tokens#8]
stop stealing tokens dickhead

not cool unoriginal cyka

du fitta

**Comment by ghost** [comment]
> stop stealing tokens dickhead

explain the "stealing" part then: https://github.blog/2019-08-19-github-token-scanning-one-billion-tokens-identified-and-five-new-partners/

**Comment by unknownsrc** [comment]
Pabszito out for blood god damn

**Comment by skidmaster69420** [comment]
THE INTERNATIONAL LANGUAGE ASSOCIATION 
T.I.L.A 

FORMAL REPLY: VIOLATION OF 3 LANGUAGES.

We must inform you that your post has insulted 3 languages simultaneously. Russia, German, English. 
Your message has been flagged by our hyper intelligent A.I. You have been classified threat level: MAX.
We must now ask you to never write any messages ever, or you might be detained by your local police district. 
This action is legally valid after it was verified by 42 Language Scientists... which passed away shortly after. 
The cause of their death was your message. 

Please spare all of us and leave the internet at once.
Goodbye.
